version: '3.8'
services:
    alertmanager:
        image: prom/alertmanager:${ALERTMANAGER_VERSION:-latest}
        restart: unless-stopped
        command:
            - '--config.file=/etc/alertmanager/alertmanager.yml'
            - '--storage.path=/alertmanager'
        volumes:
            - ./alertmanager-alertmanager.yml:/etc/alertmanager/alertmanager.yml
            - alertmanager_data:/alertmanager
        ports:
            - '${ALERTMANAGER_PORT:-9093}:9093'
        networks:
            - devnet
        healthcheck:
            test: ['CMD', 'wget', '-qO-', 'http://localhost:9093/-/ready']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    alertmanager_data:

networks:
    devnet:
        name: devnet
