version: '3.8'
services:
    promtail:
        image: grafana/promtail:${PROMTAIL_VERSION:-latest}
        restart: unless-stopped
        command: -config.file=/etc/promtail/promtail-config.yaml
        volumes:
            - ./promtail-config-promtail.yaml:/etc/promtail/promtail-config.yaml
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - loki
        networks:
            - devnet
        healthcheck:
            test: ['CMD', 'wget', '-qO-', 'http://localhost:9080/ready']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

networks:
    devnet:
        name: devnet
