version: '3.8'

services:
    sqlserver{{cs.CS_INSTANCE_SUFFIX}}:
        image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION:-{{cs.MSSQL_VERSION}}}
        restart: unless-stopped
        volumes:
            - sqlserver-data{{cs.CS_INSTANCE_SUFFIX}}:/var/opt/mssql
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-{{cs.MSSQL_SA_PASSWORD}}}
            MSSQL_PID: ${MSSQL_PID:-{{cs.MSSQL_PID}}}
        ports:
            - '${MSSQL_PORT:-{{cs.MSSQL_PORT}}}:1433'
        networks:
            - devnet
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${MSSQL_SA_PASSWORD:-{{cs.MSSQL_SA_PASSWORD}}}' -Q 'SELECT 1' -No || exit 1",
                ]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 60s

volumes:
    sqlserver-data{{cs.CS_INSTANCE_SUFFIX}}:

networks:
    devnet:
        name: devnet
