/**
 * Tests for services export utilities (services.md and env.local.example generation)
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { generateServicesMarkdown, generateEnvLocalExample } from '../utils/services-export.js';
import type { OverlayMetadata } from '../schema/types.js';

const postgresOverlay: OverlayMetadata = {
    id: 'postgres',
    name: 'PostgreSQL',
    description: 'PostgreSQL 16 database',
    category: 'database',
    ports: [
        {
            port: 5432,
            service: 'postgres',
            protocol: 'tcp',
            description: 'PostgreSQL database connection',
            onAutoForward: 'notify',
            connectionStringTemplate:
                'postgresql://{postgres_user}:{postgres_password}@{host}:{port}/{postgres_db}',
        },
    ],
};

const redisOverlay: OverlayMetadata = {
    id: 'redis',
    name: 'Redis',
    description: 'Redis 7 cache',
    category: 'database',
    ports: [
        {
            port: 6379,
            service: 'redis',
            protocol: 'tcp',
            description: 'Redis server connection',
            onAutoForward: 'notify',
            connectionStringTemplate: 'redis://{host}:{port}',
        },
    ],
};

const grafanaOverlay: OverlayMetadata = {
    id: 'grafana',
    name: 'Grafana',
    description: 'Observability visualization dashboard',
    category: 'observability',
    ports: [
        {
            port: 3000,
            service: 'grafana',
            protocol: 'http',
            description: 'Grafana web UI',
            path: '/',
            onAutoForward: 'openBrowser',
        },
    ],
};

const nodejsOverlay: OverlayMetadata = {
    id: 'nodejs',
    name: 'Node.js',
    description: 'Node.js runtime',
    category: 'language',
    ports: [],
};

describe('generateServicesMarkdown', () => {
    it('should return empty string when no overlays have ports', () => {
        const result = generateServicesMarkdown([nodejsOverlay], 0, {});
        expect(result).toBe('');
    });

    it('should include title and header', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('# Services Reference');
        expect(result).toContain('Auto-generated by Container Superposition');
    });

    it('should include Quick Links table', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('## Quick Links');
        expect(result).toContain('| Service | URL / Connection | Credentials |');
        expect(result).toContain('PostgreSQL');
    });

    it('should include Service Details section', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('## Service Details');
        expect(result).toContain('### PostgreSQL');
    });

    it('should include connection information for TCP services', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('**Connection Information:**');
        expect(result).toContain('Host (from container): `postgres`');
        expect(result).toContain('Host (from host): `localhost`');
        expect(result).toContain('Port: `5432`');
    });

    it('should include access info for HTTP services', () => {
        const result = generateServicesMarkdown([grafanaOverlay], 0, {});
        expect(result).toContain('**Access:**');
        expect(result).toContain('http://localhost:3000/');
    });

    it('should include connection strings', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {
            postgres_user: 'postgres',
            postgres_password: 'postgres',
            postgres_db: 'devdb',
        });
        expect(result).toContain('**Connection Strings:**');
    });

    it('should include code examples for known services', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('**Code Examples:**');
        expect(result).toContain('Node.js');
        expect(result).toContain('Python');
        expect(result).toContain("require('pg')");
        expect(result).toContain('psycopg2');
    });

    it('should include code examples for redis', () => {
        const result = generateServicesMarkdown([redisOverlay], 0, {});
        expect(result).toContain('**Code Examples:**');
        expect(result).toContain("require('redis')");
        expect(result).toContain('import redis');
    });

    it('should include common commands for known services', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('**Common Commands:**');
        expect(result).toContain('psql -h postgres');
    });

    it('should include health check section', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('**Health Check:**');
        expect(result).toContain('docker-compose ps postgres');
    });

    it('should include port offset section', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('## Port Offset');
        expect(result).toContain('**Current offset:** 0');
    });

    it('should show offset note when portOffset > 0', () => {
        const result = generateServicesMarkdown([postgresOverlay], 100, {});
        expect(result).toContain('**Current offset:** 100');
        expect(result).toContain('port offset of **100**');
    });

    it('should apply port offset to actual ports', () => {
        const result = generateServicesMarkdown([postgresOverlay], 100, {});
        // Actual port should be 5532 (5432 + 100)
        expect(result).toContain('5532');
    });

    it('should include troubleshooting section', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('## Troubleshooting');
        expect(result).toContain("Service won't start");
        expect(result).toContain('Connection refused');
        expect(result).toContain('Port already in use');
    });

    it('should include environment variables section', () => {
        const result = generateServicesMarkdown([postgresOverlay], 0, {});
        expect(result).toContain('## Environment Variables');
        expect(result).toContain('.env.example');
    });

    it('should include generated timestamp', () => {
        const ts = '2026-01-01T00:00:00.000Z';
        const result = generateServicesMarkdown([postgresOverlay], 0, {}, ts);
        expect(result).toContain(ts);
    });

    it('should handle multiple overlays', () => {
        const result = generateServicesMarkdown(
            [postgresOverlay, redisOverlay, grafanaOverlay],
            0,
            {}
        );
        expect(result).toContain('PostgreSQL');
        expect(result).toContain('Redis');
        expect(result).toContain('Grafana');
    });

    it('should skip overlays without ports (e.g., language overlays)', () => {
        const result = generateServicesMarkdown([postgresOverlay, nodejsOverlay], 0, {});
        expect(result).not.toContain('### Node.js');
        expect(result).toContain('### PostgreSQL');
    });

    it('should include "what would change" section for zero offset', () => {
        const result = generateServicesMarkdown([postgresOverlay, redisOverlay], 0, {});
        expect(result).toContain('5432 → 5532');
        expect(result).toContain('6379 → 6479');
    });
});

describe('generateEnvLocalExample', () => {
    let tmpDir: string;

    beforeEach(() => {
        tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'services-export-test-'));
        // Create fake overlay dirs with .env.example files
        fs.mkdirSync(path.join(tmpDir, 'postgres'), { recursive: true });
        fs.writeFileSync(
            path.join(tmpDir, 'postgres', '.env.example'),
            '# PostgreSQL Configuration\nPOSTGRES_VERSION=16\nPOSTGRES_DB=devdb\nPOSTGRES_USER=postgres\nPOSTGRES_PASSWORD=postgres\nPOSTGRES_PORT=5432\n'
        );
        fs.mkdirSync(path.join(tmpDir, 'redis'), { recursive: true });
        fs.writeFileSync(
            path.join(tmpDir, 'redis', '.env.example'),
            '# Redis Configuration\nREDIS_VERSION=7\nREDIS_PORT=6379\n'
        );
        fs.mkdirSync(path.join(tmpDir, 'nodejs'), { recursive: true });
        // nodejs has no .env.example
    });

    afterEach(() => {
        fs.rmSync(tmpDir, { recursive: true, force: true });
    });

    it('should return empty string when no overlays have .env.example', () => {
        const result = generateEnvLocalExample([nodejsOverlay], tmpDir, 0);
        expect(result).toBe('');
    });

    it('should include header with instructions', () => {
        const result = generateEnvLocalExample([postgresOverlay], tmpDir, 0);
        expect(result).toContain('Local Environment Configuration');
        expect(result).toContain('OPTIONAL overrides');
        expect(result).toContain('Generated by container-superposition');
    });

    it('should group vars by overlay with section headers', () => {
        const result = generateEnvLocalExample([postgresOverlay], tmpDir, 0);
        expect(result).toContain('# PostgreSQL');
        expect(result).toContain('# ============');
    });

    it('should comment out all variable assignments', () => {
        const result = generateEnvLocalExample([postgresOverlay], tmpDir, 0);
        // Original: POSTGRES_DB=devdb -> commented: # POSTGRES_DB=devdb
        expect(result).toContain('# POSTGRES_DB=devdb');
        expect(result).toContain('# POSTGRES_USER=postgres');
        expect(result).toContain('# POSTGRES_PASSWORD=postgres');
        // Should NOT have uncommented variable assignments
        expect(result).not.toMatch(/^POSTGRES_/m);
    });

    it('should handle multiple overlays', () => {
        const result = generateEnvLocalExample([postgresOverlay, redisOverlay], tmpDir, 0);
        expect(result).toContain('# PostgreSQL');
        expect(result).toContain('# Redis');
        expect(result).toContain('# POSTGRES_DB=devdb');
        expect(result).toContain('# REDIS_PORT=6379');
    });

    it('should skip overlays without .env.example', () => {
        const result = generateEnvLocalExample(
            [postgresOverlay, nodejsOverlay, redisOverlay],
            tmpDir,
            0
        );
        expect(result).toContain('# PostgreSQL');
        expect(result).toContain('# Redis');
        expect(result).not.toContain('# Node.js'); // no .env.example for nodejs
    });

    it('should include port offset note when offset > 0', () => {
        const result = generateEnvLocalExample([postgresOverlay], tmpDir, 100);
        expect(result).toContain('port offset of 100');
    });

    it('should preserve existing comment lines (but not comment them twice)', () => {
        const result = generateEnvLocalExample([postgresOverlay], tmpDir, 0);
        // The "# PostgreSQL Configuration" comment in .env.example should remain a comment (not double-commented)
        // It's a comment line in the source so it stays as-is
        expect(result).toContain('# PostgreSQL Configuration');
        expect(result).not.toContain('# # PostgreSQL Configuration');
    });
});
