version: '3.8'

services:
    redis{{cs.CS_INSTANCE_SUFFIX}}:
        image: redis:${REDIS_VERSION:-{{cs.REDIS_VERSION}}}-alpine
        restart: unless-stopped
        volumes:
            - redis-data{{cs.CS_INSTANCE_SUFFIX}}:/data
        ports:
            - '${REDIS_PORT:-{{cs.REDIS_PORT}}}:6379'
        command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass "$REDIS_PASSWORD"}
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD:-{{cs.REDIS_PASSWORD}}}
        networks:
            - devnet
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

volumes:
    redis-data{{cs.CS_INSTANCE_SUFFIX}}:

networks:
    devnet:
        name: devnet
