version: '3.8'
services:
    otel-collector:
        image: otel/opentelemetry-collector-contrib:${OTEL_COLLECTOR_VERSION:-latest}
        restart: unless-stopped
        command: ['--config=/etc/otel-collector-config.yaml']
        volumes:
            - ./otel-collector-config-otel-collector.yaml:/etc/otel-collector-config.yaml
        ports:
            - '${OTEL_GRPC_PORT:-4317}:4317' # OTLP gRPC receiver
            - '${OTEL_HTTP_PORT:-4318}:4318' # OTLP HTTP receiver
            - '${OTEL_METRICS_PORT:-8888}:8888' # Prometheus metrics exposed by collector
            - '${OTEL_EXPORTER_PORT:-8889}:8889' # Prometheus exporter
            - '${OTEL_HEALTH_PORT:-13133}:13133' # health_check extension
        networks:
            - devnet
        healthcheck:
            test: ['CMD', 'wget', '-qO-', 'http://localhost:13133/']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s

networks:
    devnet:
