version: '3.8'

services:
    ollama:
        image: ollama/ollama:${OLLAMA_VERSION:-latest}
        restart: unless-stopped
        volumes:
            - ${OLLAMA_MODELS_PATH:-~/.ollama}:/root/.ollama
        environment:
            - OLLAMA_HOST=0.0.0.0
        ports:
            - '${OLLAMA_PORT:-11434}:11434'
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        networks:
            - devnet

networks:
    devnet:
        name: devnet
